-define(RECEIVE_CLIENT_SUP,receive_client_sup).
-define(RECEIVE_CLIENT_SERVER,receive_client_server).
-define(CHAT_TAB_SERVER,chat_tab_server).
-define(CHAT_TAB_SUP,chat_tab_sup).
-define(SEND_CLIENT_SERVER,send_client_server).
-define(SEND_CLIENT_SUP,send_client_sup).
-define(CHAT_SERVER,chat_server3).
-define(MSG_SERVER,msg_server).
-define(LOGIN_TAG,"bG9naW4=").
-define(SWITCH_TAG,"c3dpdGNo").
-record(player, {name,zone="world",time=none}).